import { ClientLayout } from "./ClientLayout";
import "./globals.css";

import backImage from "@/assets/back2.jpg";

export const metadata = {
  title: "Next todolist",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` bg-center `}
        style={{ backgroundImage: `url(${backImage.src})` }}
      >
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
